eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
    instance:
        preferIpAddress: true
        
server:
    port: 8762

spring:
    cloud:
        inetutils:
            preferredNetworks: 192.168
