eureka:
    client:
        register-with-eureka: false
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/, http://localhost:8760/eureka/

server:
    port: 8763
    
spring:
    application:
        name: eureka-consumer